pipeline {
  agent any
 
  tools {nodejs "node"}
 
  stages {
    stage('Build') {
      steps {
        build job: 'nodejs-template', propagate: true, parameters: [[$class: 'StringParameterValue', name: 'REPO', value: 'https://github.com/urielsalis/node-baas'], [$class: 'StringParameterValue', name: 'name', value: '${env.JOB_NAME}-${env.BUILD_NUMBER}']]      }
    }

    stage('Create AMI') {
      steps {
        build job: 'nodejs-template-ami', propagate: true, parameters: [[$class: 'StringParameterValue', name: 'NAME', value: '${env.JOB_NAME}-${env.BUILD_NUMBER}']]
      }
    }
  }
}
